### ISSUE TITLE
User Profile in Top Right No Action

### ISSUE THREAD

**Issue by BTCarpenter** [pastorryanhayden/sermons#46]
Action is inconsistent, sometimes there's a dropdown with church settings on hover of user icon. Other times no action either by hover or click.

On First page load action works properly, after navigating to another section, the dropdown will not open.

Also appears that after navigating to other sections (sermons, series, speakers, etc.) Pure Chat is no longer visible

![Annotation 2019-11-04 122653](https://user-images.githubusercontent.com/16262496/68142956-6cadf980-fefe-11e9-87ed-f2aec06cc519.png)

**Comment by pastorryanhayden** [comment]
I'm thinking this has something to do with Turbolinks.  I'm going to fix it.
