### ISSUE TITLE
Church Tools Homepage Sign Up Buttons

### ISSUE THREAD

**Issue by BTCarpenter** [pastorryanhayden/sermons#47]
### Sign Up button in the hero area isn't clickable (from desktop / Chrome).

Via Inspector added class `z-40` and that allowed it to work. Not sure if that is the correct solution. 

Works correctly on mobile (Iphone 6s Plus)
Does not work on tablet (Ipad 9.7 in)

![Annotation 2019-11-04 122918](https://user-images.githubusercontent.com/16262496/68143144-d5957180-fefe-11e9-8e70-125d1a953226.png)

### Sign Up Buttons do not point to same place

Top & Hero > /register
Bottom > /terms

Also, terms page does not show check boxes as before

![Annotation 2019-11-04 123649](https://user-images.githubusercontent.com/16262496/68143600-ccf16b00-feff-11e9-9348-680b209af482.png)

**Comment by pastorryanhayden** [comment]
Closed by 243883a

**Comment by pastorryanhayden** [comment]
@BTCarpenter The terms thing intentional.  I've refactored the whole registrationg flow to have a lot less friction.

**Comment by BTCarpenter** [comment]
Yeah, totally with you on the terms. I see the one registration page now with the agreement to terms and statement of faith. 

For some reason the Hero Sign Up Button is still not clickable for me on desktop
